# Generated by Django 4.0.3 on 2022-09-25 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_new',
            fields=[
                ('sr_no', models.IntegerField(default=True)),
                ('pm_kisan_id', models.CharField(default=True, max_length=11)),
                ('aadhaar_no', models.CharField(default=True, max_length=12, primary_key=True, serialize=False)),
                ('bank_ifsc', models.CharField(default=True, max_length=11)),
                ('bank_acc_number', models.CharField(default=True, max_length=16)),
                ('username', models.TextField(default=True)),
                ('createdby_tehsildar', models.TextField(default=True)),
                ('farmer_name', models.CharField(default=True, max_length=100)),
                ('farmer_father_name', models.TextField(default=True)),
                ('khata_number', models.IntegerField(default=True)),
                ('khasra_number', models.TextField(default=True)),
                ('is_active', models.CharField(default=True, max_length=1)),
                ('state_code', models.CharField(default=True, max_length=20)),
                ('district_code', models.CharField(default=True, max_length=100)),
                ('tehsil_code', models.CharField(default=True, max_length=4)),
                ('land_area_unit', models.TextField(default=True, max_length=100)),
                ('land_area', models.TextField(default=True, max_length=50)),
                ('creation_timestamp', models.DateTimeField(default=True)),
                ('land_block_code', models.TextField(default=True)),
                ('land_location', models.CharField(default=True, max_length=100)),
                ('type_of_mutation', models.CharField(default=True, max_length=100)),
                ('date_of_mutation', models.DateField(default=True)),
                ('land_ownership_type', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
