# Generated by Django 4.0.3 on 2022-06-24 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='district_collectors',
            fields=[
                ('sr_no', models.IntegerField()),
                ('collector_name', models.CharField(max_length=100)),
                ('collector_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField()),
                ('is_active', models.CharField(max_length=1)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='districts',
            fields=[
                ('sr_no', models.IntegerField()),
                ('district_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('district_name_eng', models.TextField()),
                ('district_name_local', models.TextField()),
                ('census_2001', models.CharField(max_length=2)),
                ('census_2011', models.CharField(max_length=3)),
                ('district_version', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='nic_admin',
            fields=[
                ('name', models.TextField()),
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='state_admin',
            fields=[
                ('joint_commissioner', models.TextField()),
                ('creation_timestamp', models.DateTimeField()),
                ('uid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tehsil',
            fields=[
                ('sr_no', models.IntegerField()),
                ('tehsil_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('tehsil_name_eng', models.TextField()),
                ('tehsil_name_local', models.TextField()),
                ('census_2001', models.CharField(max_length=2)),
                ('census_2011', models.CharField(max_length=3)),
                ('tehsil_version', models.CharField(max_length=1)),
                ('district_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='tehsildars',
            fields=[
                ('sr_no', models.IntegerField()),
                ('tehsildar_name', models.CharField(max_length=100)),
                ('tehsildar_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField()),
                ('is_active', models.CharField(max_length=1)),
                ('tehsil_code', models.TextField()),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
